export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_NETWORK = 'UPDATE_NETWORK'

export const SET_CONTRACT = 'SET_CONTRACT'
export const UPDATE_BALANCE = 'UPDATE_BALANCE'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
